spring:
  application:
    name: Customers application
  datasource:
    url: jdbc:h2:mem::customersapp.db;DB_CLOSE_DELAY=-1;MODE=MySQL;MV_STORE=FALSE;MVCC=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        id.new_generator_mappings: true
        generate_statistics: false
        cache:
          use_second_level_cache: false
          use_query_cache: false
    show-sql: true
  liquibase:
    change-log: classpath:/changelog/master.xml
    enabled: true
  h2:
    console:
      enabled: true
      path: /h2console

